# Generated by Django 5.1.4 on 2024-12-10 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.CharField(max_length=225)),
                ('skill_learn', models.JSONField(blank=True, default=list)),
                ('group_members', models.ManyToManyField(related_name='group_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
