# Generated by Django 5.1.4 on 2024-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ManyToManyField(blank=True, related_name='todo', to='Group.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group_name',
            field=models.ManyToManyField(blank=True, related_name='tasks_list', to='Group.group'),
        ),
    ]
